// Code generated by "stringer -type=City -linecomment"; DO NOT EDIT.

package renthouse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Taipei-0]
	_ = x[NewTaipei-1]
}

const _City_name = "台北新北"

var _City_index = [...]uint8{0, 6, 12}

func (i City) String() string {
	if i < 0 || i >= City(len(_City_index)-1) {
		return "City(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _City_name[_City_index[i]:_City_index[i+1]]
}
