// Code generated by "stringer -type=District -linecomment"; DO NOT EDIT.

package renthouse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Banqiao-0]
	_ = x[Sanchong-1]
	_ = x[Tamsui-2]
	_ = x[Zhonghe-3]
	_ = x[Yonghe-4]
	_ = x[Xizhi-5]
	_ = x[Xindian-6]
	_ = x[Tucheng-7]
	_ = x[Sanxia-8]
	_ = x[Shulin-9]
	_ = x[Yingge-10]
	_ = x[Xinzhuang-11]
	_ = x[Taishan-12]
	_ = x[Linkou-13]
	_ = x[Luzhou-14]
	_ = x[Wugu-15]
}

const _District_name = "板橋三重淡水中和永和汐止新店土城三峽樹林鶯歌新莊泰山林口蘆洲五股"

var _District_index = [...]uint8{0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96}

func (i District) String() string {
	if i < 0 || i >= District(len(_District_index)-1) {
		return "District(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _District_name[_District_index[i]:_District_index[i+1]]
}
